#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

source "$(dirname ${0})"/settings

# Refresh

# Start by wiping the working area
"$(dirname ${0})"/wipe || exit 1

# Recreate the working area and go to it
mkdir -p "${BUILD_workarea_path}"/build || exit 1
cd "${BUILD_workarea_path}"/build || exit 1

# Startup GNU Autotools
autoreconf --install "${BUILD_project_path}" || exit 1

# Configure the project
"${BUILD_project_path}"/configure --enable-silent-rules --prefix="${BUILD_workarea_path}"
