#!/usr/bin/bash

[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1

source "$(dirname ${0})"/settings

# Run

# Build and run
"$(dirname ${0})"/build || exit 1
"${BUILD_workarea_path}"/bin/${BUILD_project} "$@"
